### ISSUE TITLE
Done

### ISSUE THREAD

**Issue by ingra14m** [CUHK-AIM-Group/EndoSparse#1]
Thanks the authors for their kind response!

**Comment by chenxinli001** [comment]
We will update a arxiv version to include the citation of Deformable-GS.

**Comment by chenxinli001** [comment]
Some other clarification: I understand you may be feeling frustrated today, but don't you agree that a respectful and polite approach is more conducive to communication and problem-solving? At the same time, I want to express that I understand and sympathize with your feelings. I acknowledge that proper recognition in academia is indeed very important.

In fact:

Regarding your point about Deformable-GS seemingly being published before D-4DGS but not receiving wider recognition, this is something I have no control over. We were only aware of D-4DGS, and D-4DGS did not mention Deformable-GS in their repository. In academia, researchers are not required to be aware of ALL existing work, aren't they? Regarding your call for supporting original contributions, it might be better addressed by communicating directly with contemporaneous works like 4DGS.

Concerning your previous help, you mentioned a depth-diff-gaussian-rasterization library in an issue on the EndoGaussian repository. However, this alone doesn't logically lead to the conclusion that you are the author of Deformable-GS or that you wanted us to cite Deformable-GS. So it seems there was no malicious intent in not citing Deformable-GS in the original version of arxiv.

**Comment by ingra14m** [comment]
Some interesting observations: 
- Difference between the first and second version of D-4DGS
(the second version on arxiv and the CVPR camera ready version)
![4c2426c3d719bbb7e0733e8ec430a4bc](https://github.com/CUHK-AIM-Group/EndoSparse/assets/63096187/0e6c56d2-35ed-4b84-a713-13a7d6e34542)
(the first version on arxiv)
![b7b7313b876d93337e890a8dfeb86652](https://github.com/CUHK-AIM-Group/EndoSparse/assets/63096187/6a32438c-4f92-4d18-a636-fe14281d0317)
- Different rendering quality between the two methods on datasets with accurate camera poses
(Deformable-GS)
![b4f10001d3dee727c4272ab3c170566f](https://github.com/CUHK-AIM-Group/EndoSparse/assets/63096187/6675ad8e-2652-456b-b1de-0eb94afe3ec2)
(D-4DGS)
![1715d6f0b8ba18d6626ae2c9ab03b48a](https://github.com/CUHK-AIM-Group/EndoSparse/assets/63096187/cf13523a-3009-48cc-82e5-0bd150bc99c5)

I believe that if you are objective enough, you will find that Deformable-GS is the state of the art (SOTA), not D-4DGS. If you observe more closely, you will see that D-4DGS directly copied the per-scene metrics of K-plane from Deformable-GS. I believe it shouldn't be difficult to understand why they didn't mention our method in their repo, even though they used our rasterizer. 

Researchers do not need to know every single work, but they need to understand the SOTA, need to know the first one, and need to recognize that [the one from fdu](https://github.com/fudan-zvg/4d-gaussian-splatting) is the true 4DGS.

**Comment by chenxinli001** [comment]
You're right. 😊
