### ISSUE TITLE
Inquiry About Code Release

### ISSUE THREAD

**Issue by VinyehShaw** [CUHK-AIM-Group/EndoSparse#2]
Hi there,

I am very interested in your work and I am looking forward to exploring the code. Could you please let me know when you plan to open source the code? Will it be available by the time of the MICCAI conference?

Thank you for your time and effort.

Best regards

**Comment by chenxinli001** [comment]
Thank you for your interest. We're going to work on preparing a simple avaliable demo code, which we hope to release before MICCAI. While we can't guarantee it, there may be a good chance we'll have something available by then. We appreciate your patience and enthusiasm.
